import type { CalibrationProfile, MockScenario, ProvenanceSummary, ValidationSummary } from './types'

function provenance(sourceType: ProvenanceSummary['sourceType'], confidenceNote: string): ProvenanceSummary {
  return {
    sourceType,
    sourceReference: 'shop-floor calibration notebook',
    method: sourceType === 'estimated' ? 'manual estimate' : 'bench measurement',
    measuredAt: '2026-03-21T14:10:00Z',
    confidenceNote,
  }
}

function validationSummary(
  overallValidity: ValidationSummary['overallValidity'],
  warnings: string[],
  recommendedActions: string[],
  sectionValidity: ValidationSummary['sectionValidity'],
): ValidationSummary {
  return {
    overallValidity,
    sectionValidity,
    warnings,
    errors: overallValidity === 'failed_validation' ? ['Profile is not safe to use for trusted analysis.'] : [],
    recommendedActions,
    evaluatedAt: '2026-03-22T08:20:00Z',
  }
}

export const mockSessionScenarios: MockScenario[] = [
  {
    id: 'ready-session',
    label: 'Clean import',
    eyebrow: 'Usable session',
    summary: 'All mandatory channels detected and timing looks coherent.',
    result: {
      sessionId: 'session-001',
      status: 'ready',
      sessionSummary: {
        sessionLabel: 'Washboards / clicker baseline',
        sourceFile: '2026-03-22_moto_001.csv',
        sampleRateHz: 200,
        durationSec: 612.4,
        availableChannels: 6,
        validity: 'valid',
        validityLabel: 'ready for profile attachment',
      },
      channelDescriptors: [
        {
          channelKey: 'front-pot',
          channelLabel: 'Front potentiometer',
          rawUnit: 'V',
          sampleCount: 122480,
          signConvention: 'compression positive',
          detectedRole: 'front_travel_sensor',
          mappingState: 'mapped',
          notes: 'Strong signal with zero bounce segment at start.',
        },
        {
          channelKey: 'rear-pot',
          channelLabel: 'Rear potentiometer',
          rawUnit: 'V',
          sampleCount: 122480,
          signConvention: 'compression positive',
          detectedRole: 'rear_travel_sensor',
          mappingState: 'mapped',
          notes: 'No dropout detected over the recorded lap.',
        },
        {
          channelKey: 'imu-pitch',
          channelLabel: 'IMU pitch gyro',
          rawUnit: 'deg/s',
          sampleCount: 122480,
          signConvention: 'nose-up positive',
          detectedRole: 'pitch_gyro',
          mappingState: 'mapped',
          notes: 'Stationary launch segment suitable for bias capture.',
        },
      ],
      importWarnings: ['No issues that block a trusted calibration workflow.'],
      importDiagnostics: [
        'Delimiter inferred as comma with stable header row.',
        'Timestamp spacing standard deviation below 0.1 ms.',
      ],
    },
  },
  {
    id: 'warning-session',
    label: 'Warning state',
    eyebrow: 'Usable but flagged',
    summary: 'Pitch channel is present but the stationary bias window is weak.',
    result: {
      sessionId: 'session-002',
      status: 'warning',
      sessionSummary: {
        sessionLabel: 'Rock garden / fork spring test',
        sourceFile: '2026-03-22_moto_002.csv',
        sampleRateHz: 100,
        durationSec: 447.1,
        availableChannels: 5,
        validity: 'valid_estimated',
        validityLabel: 'usable with provisional pitch confidence',
      },
      channelDescriptors: [
        {
          channelKey: 'front-pot',
          channelLabel: 'Front potentiometer',
          rawUnit: 'V',
          sampleCount: 44710,
          signConvention: 'compression positive',
          detectedRole: 'front_travel_sensor',
          mappingState: 'mapped',
          notes: 'Minor clipping at maximum extension.',
        },
        {
          channelKey: 'rear-pot',
          channelLabel: 'Rear potentiometer',
          rawUnit: 'V',
          sampleCount: 44710,
          signConvention: 'compression positive',
          detectedRole: 'rear_travel_sensor',
          mappingState: 'mapped',
          notes: 'Channel health good.',
        },
        {
          channelKey: 'imu-pitch',
          channelLabel: 'IMU pitch gyro',
          rawUnit: 'deg/s',
          sampleCount: 44710,
          signConvention: 'nose-up positive',
          detectedRole: 'pitch_gyro',
          mappingState: 'needs-review',
          notes: 'Bias capture segment shorter than preferred threshold.',
        },
      ],
      importWarnings: [
        'Pitch gyro bias window is short; downstream pitch traces should be flagged as provisional.',
      ],
      importDiagnostics: [
        'Imported with explicit 100 Hz override from file metadata.',
        'One short timestamp gap was repaired during import.',
      ],
    },
  },
  {
    id: 'failed-session',
    label: 'Failed import',
    eyebrow: 'Blocked state',
    summary: 'Mandatory rear travel signal is missing, so analysis cannot be trusted.',
    result: {
      sessionId: 'session-003',
      status: 'failed',
      sessionSummary: {
        sessionLabel: 'Corrupted logger dump',
        sourceFile: '2026-03-22_moto_003.csv',
        sampleRateHz: 50,
        durationSec: 381.6,
        availableChannels: 3,
        validity: 'failed_validation',
        validityLabel: 'missing mandatory channels',
      },
      channelDescriptors: [
        {
          channelKey: 'front-pot',
          channelLabel: 'Front potentiometer',
          rawUnit: 'V',
          sampleCount: 19080,
          signConvention: 'compression positive',
          detectedRole: 'front_travel_sensor',
          mappingState: 'mapped',
          notes: 'Usable front signal.',
        },
        {
          channelKey: 'rear-pot',
          channelLabel: 'Rear potentiometer',
          rawUnit: 'V',
          sampleCount: 0,
          signConvention: 'compression positive',
          detectedRole: 'rear_travel_sensor',
          mappingState: 'missing',
          notes: 'Channel header found but no samples recorded.',
        },
      ],
      importWarnings: [
        'Rear travel signal is absent. Calibration may be edited, but trusted analysis is blocked.',
      ],
      importDiagnostics: [
        'File parsed successfully but one mandatory series is empty.',
        'Use logger health checks before attempting another capture.',
      ],
    },
  },
]

export const mockProfiles: CalibrationProfile[] = [
  {
    profileId: 'profile-baseline',
    profileName: 'TE300 / sand baseline',
    schemaVersion: '1.0.0',
    bikeMetadata: {
      manufacturer: 'Husqvarna',
      model: 'TE 300',
      modelYear: 2024,
      configurationName: 'spring baseline',
      frontTravelMm: 300,
      rearTravelMm: 310,
      sensorPackage: 'fork + shock pots, IMU, accel',
    },
    channelMapping: {
      frontSensorChannel: 'front-pot',
      rearSensorChannel: 'rear-pot',
      pitchGyroChannel: 'imu-pitch',
      longitudinalAccelChannel: 'imu-ax',
      sampleRateHz: 200,
      mappingValidity: 'valid',
    },
    frontTravelConfig: {
      offsetVolts: 0.42,
      calibrationFactorMmPerVolt: 57.8,
      forkAngleDeg: 27.5,
      maxTravelMm: 300,
      compressionSign: 'positive',
      fitMetrics: 'RMS residual 1.2 mm over 8 points',
      validity: 'valid',
      provenance: provenance('measured', 'Bench-measured against travel stops.'),
    },
    rearTravelConfig: {
      offsetVolts: 0.37,
      calibrationFactorMmPerVolt: 18.4,
      linkageModelType: 'quadratic',
      linkageCoefficients: [0.021, 2.41, -1.8],
      maxTravelMm: 310,
      compressionSign: 'positive',
      sensorFitMetrics: 'Shock stroke fit RMS 0.8 mm',
      linkageFitMetrics: 'Wheel travel fit RMS 2.3 mm',
      validity: 'valid',
      provenance: provenance('fitted', 'Linkage fit backed by 10 measured shock-travel pairs.'),
    },
    velocityProcessingConfig: {
      sourceChannel: 'front-pot',
      differentiationMethod: 'central difference',
      preFilter: { type: 'Butterworth', cutoffHz: 20, order: 2 },
      postFilter: { type: 'Savitzky-Golay', cutoffHz: 18, order: 3 },
      sampleRateHz: 200,
      validity: 'valid',
      provenance: provenance('measured', 'Filter settings validated against curb-drop capture.'),
    },
    pitchProcessingConfig: {
      gyroAxis: 'pitch_z',
      gyroBias: 0.012,
      initialPitchDeg: -1.5,
      signConvention: 'nose-up positive',
      driftControl: 'stationary bias + low-rate trim',
      validity: 'valid',
      provenance: provenance('measured', 'Bias captured from 4-second standstill segment.'),
    },
    histogramSettings: {
      frontTravelMaxMm: 300,
      rearTravelMaxMm: 310,
      binCount: 100,
      binWidth: 3.1,
      bottomOutThresholdPct: 95,
      topOutThresholdPct: 5,
      validity: 'valid',
    },
    validationSummary: validationSummary(
      'valid',
      ['All core sections complete. Travel and dynamic outputs may be trusted for Phase 2 graph work.'],
      ['Freeze graph payload shapes before building histogram components.'],
      {
        channelMapping: 'valid',
        frontTravel: 'valid',
        rearTravel: 'valid',
        velocityProcessing: 'valid',
        pitchProcessing: 'valid',
      },
    ),
    provenanceSummary: provenance('measured', 'Profile anchored to measured constants and fitted rear linkage.'),
    revisionMetadata: {
      revision: 3,
      updatedAt: '2026-03-22T07:10:00Z',
      updatedBy: 'rickm',
    },
  },
  {
    profileId: 'profile-provisional',
    profileName: 'TE300 / woods provisional',
    schemaVersion: '1.0.0',
    bikeMetadata: {
      manufacturer: 'Husqvarna',
      model: 'TE 300',
      modelYear: 2024,
      configurationName: 'wet-root setup',
      frontTravelMm: 300,
      rearTravelMm: 310,
      sensorPackage: 'fork + shock pots, IMU, accel',
    },
    channelMapping: {
      frontSensorChannel: 'front-pot',
      rearSensorChannel: 'rear-pot',
      pitchGyroChannel: 'imu-pitch',
      longitudinalAccelChannel: 'imu-ax',
      sampleRateHz: 100,
      mappingValidity: 'valid_estimated',
    },
    frontTravelConfig: {
      offsetVolts: 0.39,
      calibrationFactorMmPerVolt: 56.4,
      forkAngleDeg: 27.5,
      maxTravelMm: 300,
      compressionSign: 'positive',
      fitMetrics: 'RMS residual 2.1 mm over 4 points',
      validity: 'valid_estimated',
      provenance: provenance('estimated', 'Offset estimated from static sag rather than bench zero.'),
    },
    rearTravelConfig: {
      offsetVolts: 0.34,
      calibrationFactorMmPerVolt: 18.0,
      linkageModelType: 'quadratic',
      linkageCoefficients: [0.018, 2.28, -0.9],
      maxTravelMm: 310,
      compressionSign: 'positive',
      sensorFitMetrics: 'Shock stroke fit RMS 1.4 mm',
      linkageFitMetrics: 'Wheel travel fit RMS 4.9 mm',
      validity: 'valid_estimated',
      provenance: provenance('estimated', 'Linkage fit extrapolated from limited stroke-travel points.'),
    },
    velocityProcessingConfig: {
      sourceChannel: 'front-pot',
      differentiationMethod: 'central difference',
      preFilter: { type: 'Butterworth', cutoffHz: 12, order: 2 },
      postFilter: { type: 'Butterworth', cutoffHz: 10, order: 2 },
      sampleRateHz: 100,
      validity: 'valid_estimated',
      provenance: provenance('estimated', 'Velocity settings copied from another profile and not ride-verified.'),
    },
    pitchProcessingConfig: {
      gyroAxis: 'pitch_z',
      gyroBias: 0.034,
      initialPitchDeg: -0.5,
      signConvention: 'nose-up positive',
      driftControl: 'manual trim only',
      validity: 'incomplete',
      provenance: provenance('estimated', 'Bias estimated after import because no clean standstill segment exists.'),
    },
    histogramSettings: {
      frontTravelMaxMm: 300,
      rearTravelMaxMm: 310,
      binCount: 100,
      binWidth: 3.1,
      bottomOutThresholdPct: 95,
      topOutThresholdPct: 5,
      validity: 'valid',
    },
    validationSummary: validationSummary(
      'valid_estimated',
      [
        'Front and rear travel can be used, but the pitch chain is provisional.',
        'Estimated constants should remain visible anywhere graphs are shown.',
      ],
      [
        'Capture a stationary gyro bias segment before trusting pitch traces.',
        'Re-run rear linkage fitting with more stroke-travel points.',
      ],
      {
        channelMapping: 'valid_estimated',
        frontTravel: 'valid_estimated',
        rearTravel: 'valid_estimated',
        velocityProcessing: 'valid_estimated',
        pitchProcessing: 'incomplete',
      },
    ),
    provenanceSummary: provenance('estimated', 'Profile remains usable but not yet defensible for final tuning calls.'),
    revisionMetadata: {
      revision: 1,
      updatedAt: '2026-03-21T19:30:00Z',
      updatedBy: 'rickm',
    },
  },
  {
    profileId: 'profile-incomplete',
    profileName: 'New rear sensor install',
    schemaVersion: '1.0.0',
    bikeMetadata: {
      manufacturer: 'Husqvarna',
      model: 'TE 300',
      modelYear: 2024,
      configurationName: 'fresh sensor retrofit',
      frontTravelMm: 300,
      rearTravelMm: 310,
      sensorPackage: 'fork + shock pots',
    },
    channelMapping: {
      frontSensorChannel: 'front-pot',
      rearSensorChannel: 'rear-pot',
      pitchGyroChannel: 'unassigned',
      longitudinalAccelChannel: 'unassigned',
      sampleRateHz: 200,
      mappingValidity: 'incomplete',
    },
    frontTravelConfig: {
      offsetVolts: 0.0,
      calibrationFactorMmPerVolt: 0.0,
      forkAngleDeg: 27.5,
      maxTravelMm: 300,
      compressionSign: 'positive',
      fitMetrics: 'No bench fit captured yet',
      validity: 'incomplete',
      provenance: provenance('imported', 'Placeholder values created during profile generation.'),
    },
    rearTravelConfig: {
      offsetVolts: 0.0,
      calibrationFactorMmPerVolt: 0.0,
      linkageModelType: 'quadratic',
      linkageCoefficients: [],
      maxTravelMm: 310,
      compressionSign: 'positive',
      sensorFitMetrics: 'No fit data entered',
      linkageFitMetrics: 'No linkage data entered',
      validity: 'failed_validation',
      provenance: provenance('imported', 'Profile created before rear calibration work began.'),
    },
    velocityProcessingConfig: {
      sourceChannel: 'front-pot',
      differentiationMethod: 'unassigned',
      preFilter: { type: 'unassigned', cutoffHz: 0, order: 0 },
      postFilter: { type: 'unassigned', cutoffHz: 0, order: 0 },
      sampleRateHz: 200,
      validity: 'incomplete',
      provenance: provenance('imported', 'No velocity processing choices saved yet.'),
    },
    pitchProcessingConfig: {
      gyroAxis: 'unassigned',
      gyroBias: 0,
      initialPitchDeg: 0,
      signConvention: 'nose-up positive',
      driftControl: 'unassigned',
      validity: 'incomplete',
      provenance: provenance('imported', 'Pitch package not configured.'),
    },
    histogramSettings: {
      frontTravelMaxMm: 300,
      rearTravelMaxMm: 310,
      binCount: 100,
      binWidth: 3.1,
      bottomOutThresholdPct: 95,
      topOutThresholdPct: 5,
      validity: 'valid',
    },
    validationSummary: validationSummary(
      'failed_validation',
      ['Profile cannot support trusted analysis because the rear travel chain is undefined.'],
      [
        'Complete front and rear travel calibration before enabling analysis.',
        'Assign IMU channels if pitch interpretation is required.',
      ],
      {
        channelMapping: 'incomplete',
        frontTravel: 'incomplete',
        rearTravel: 'failed_validation',
        velocityProcessing: 'incomplete',
        pitchProcessing: 'incomplete',
      },
    ),
    provenanceSummary: provenance('imported', 'Shell profile only; all engineering constants remain placeholders.'),
    revisionMetadata: {
      revision: 0,
      updatedAt: '2026-03-22T08:05:00Z',
      updatedBy: 'rickm',
    },
  },
]